### ISSUE TITLE
Chef not Taking Job

### ISSUE THREAD

**Issue by BobbyLinMC** [CoffeeCatRailway/HamNCheese#2]
Hello. So I have a problem with the chef. Villagers won't take the job when the chopping board is on a block. They will only accept the job when the chopping board is on the floor. I'm building a restaurant and I have to put the chopping board on the floor and it takes space and doesn't look good. So can you please fix it to make the villager take the chef profession when the chopping board is on a block? Thank you!!

**Comment by CoffeeCatRailway** [comment]
Could you provide a screenshot of where the chopping board is & where you want to place it?

**Comment by BobbyLinMC** [comment]
https://imgur.com/T9hCe0L

https://i.imgur.com/T9hCe0L.png

These are the links to Imgur. I posted the picture there. You can use both links. :)

**Comment by CoffeeCatRailway** [comment]
It could be that Minecraft checks if you can walk to the board.
I did some testing last night & found that you need an empty block above it for the villager to path find it.

**Comment by CoffeeCatRailway** [comment]
I'm working on finding a solution so you don't need an empty block above.
